//------------------------------------------------------------------------------
// <auto-generated>
//     Il codice è stato generato da uno strumento.
//     Versione runtime:4.0.30319.42000
//
//     Le modifiche apportate a questo file possono provocare un comportamento non corretto e andranno perse se
//     il codice viene rigenerato.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Progetto_Symposion
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Recensione", Namespace="http://schemas.datacontract.org/2004/07/Progetto_Symposion")]
    public partial class Recensione : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string CommentoField;
        
        private int IdField;
        
        private Progetto_Symposion.Libro LibroField;
        
        private int PunteggioField;
        
        private string UsernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Commento
        {
            get
            {
                return this.CommentoField;
            }
            set
            {
                this.CommentoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Progetto_Symposion.Libro Libro
        {
            get
            {
                return this.LibroField;
            }
            set
            {
                this.LibroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Punteggio
        {
            get
            {
                return this.PunteggioField;
            }
            set
            {
                this.PunteggioField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Libro", Namespace="http://schemas.datacontract.org/2004/07/Progetto_Symposion")]
    public partial class Libro : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int AnnoField;
        
        private string AutoreField;
        
        private string FilePathField;
        
        private Progetto_Symposion.genere GenField;
        
        private string TitoloField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Anno
        {
            get
            {
                return this.AnnoField;
            }
            set
            {
                this.AnnoField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Autore
        {
            get
            {
                return this.AutoreField;
            }
            set
            {
                this.AutoreField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FilePath
        {
            get
            {
                return this.FilePathField;
            }
            set
            {
                this.FilePathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Progetto_Symposion.genere Gen
        {
            get
            {
                return this.GenField;
            }
            set
            {
                this.GenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titolo
        {
            get
            {
                return this.TitoloField;
            }
            set
            {
                this.TitoloField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="genere", Namespace="http://schemas.datacontract.org/2004/07/Progetto_Symposion")]
    public enum genere : int
    {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Avventura = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Classici = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fantascienza = 2,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Fantasy = 3,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Giallo = 4,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Horror = 5,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Personale = 6,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Romanzo = 7,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Thriller = 8,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Umorismo = 9,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Lista", Namespace="http://schemas.datacontract.org/2004/07/Progetto_Symposion")]
    public partial class Lista : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private Progetto_Symposion.genere GenField;
        
        private int IdField;
        
        private bool IsVisibileField;
        
        private Progetto_Symposion.Libro[] ListaLibriField;
        
        private string NomeField;
        
        private string UsernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Progetto_Symposion.genere Gen
        {
            get
            {
                return this.GenField;
            }
            set
            {
                this.GenField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsVisibile
        {
            get
            {
                return this.IsVisibileField;
            }
            set
            {
                this.IsVisibileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Progetto_Symposion.Libro[] ListaLibri
        {
            get
            {
                return this.ListaLibriField;
            }
            set
            {
                this.ListaLibriField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome
        {
            get
            {
                return this.NomeField;
            }
            set
            {
                this.NomeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SegnalazioneLibro", Namespace="http://schemas.datacontract.org/2004/07/Progetto_Symposion")]
    public partial class SegnalazioneLibro : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private Progetto_Symposion.Libro LibroField;
        
        private string UsernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Progetto_Symposion.Libro Libro
        {
            get
            {
                return this.LibroField;
            }
            set
            {
                this.LibroField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SegnalazioneRecensione", Namespace="http://schemas.datacontract.org/2004/07/Progetto_Symposion")]
    public partial class SegnalazioneRecensione : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        private Progetto_Symposion.Recensione RecensioneField;
        
        private string UsernameField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Progetto_Symposion.Recensione Recensione
        {
            get
            {
                return this.RecensioneField;
            }
            set
            {
                this.RecensioneField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Username
        {
            get
            {
                return this.UsernameField;
            }
            set
            {
                this.UsernameField = value;
            }
        }
    }
}
namespace SymposionUtenteLib
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    public partial class BookFault : object, System.Runtime.Serialization.IExtensibleDataObject
    {
        
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private string MessageField;
        
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData
        {
            get
            {
                return this.extensionDataField;
            }
            set
            {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
}


[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(ConfigurationName="IUtente")]
public interface IUtente
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestisciUtente/GetRecensioniScritte", ReplyAction="http://tempuri.org/IGestisciUtente/GetRecensioniScritteResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IGestisciUtente/GetRecensioniScritteBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    Progetto_Symposion.Recensione[] GetRecensioniScritte(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestisciUtente/GetRecensioniScritte", ReplyAction="http://tempuri.org/IGestisciUtente/GetRecensioniScritteResponse")]
    System.Threading.Tasks.Task<Progetto_Symposion.Recensione[]> GetRecensioniScritteAsync(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestisciUtente/GetListePersonali", ReplyAction="http://tempuri.org/IGestisciUtente/GetListePersonaliResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IGestisciUtente/GetListePersonaliBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    Progetto_Symposion.Lista[] GetListePersonali(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestisciUtente/GetListePersonali", ReplyAction="http://tempuri.org/IGestisciUtente/GetListePersonaliResponse")]
    System.Threading.Tasks.Task<Progetto_Symposion.Lista[]> GetListePersonaliAsync(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestisciUtente/GetRecensioniSalvate", ReplyAction="http://tempuri.org/IGestisciUtente/GetRecensioniSalvateResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IGestisciUtente/GetRecensioniSalvateBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    Progetto_Symposion.Recensione[] GetRecensioniSalvate(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestisciUtente/GetRecensioniSalvate", ReplyAction="http://tempuri.org/IGestisciUtente/GetRecensioniSalvateResponse")]
    System.Threading.Tasks.Task<Progetto_Symposion.Recensione[]> GetRecensioniSalvateAsync(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestisciUtente/GetListeSalvate", ReplyAction="http://tempuri.org/IGestisciUtente/GetListeSalvateResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IGestisciUtente/GetListeSalvateBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    Progetto_Symposion.Lista[] GetListeSalvate(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGestisciUtente/GetListeSalvate", ReplyAction="http://tempuri.org/IGestisciUtente/GetListeSalvateResponse")]
    System.Threading.Tasks.Task<Progetto_Symposion.Lista[]> GetListeSalvateAsync(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecensione/PubblicaRecensione", ReplyAction="http://tempuri.org/IRecensione/PubblicaRecensioneResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IRecensione/PubblicaRecensioneBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    void PubblicaRecensione(System.Nullable<int> punteggio, string commento, Progetto_Symposion.Libro libro, string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecensione/PubblicaRecensione", ReplyAction="http://tempuri.org/IRecensione/PubblicaRecensioneResponse")]
    System.Threading.Tasks.Task PubblicaRecensioneAsync(System.Nullable<int> punteggio, string commento, Progetto_Symposion.Libro libro, string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecensione/ModificaRecensione", ReplyAction="http://tempuri.org/IRecensione/ModificaRecensioneResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IRecensione/ModificaRecensioneBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    void ModificaRecensione(Progetto_Symposion.Recensione recensione);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecensione/ModificaRecensione", ReplyAction="http://tempuri.org/IRecensione/ModificaRecensioneResponse")]
    System.Threading.Tasks.Task ModificaRecensioneAsync(Progetto_Symposion.Recensione recensione);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListePersonali/CreaListaPersonale", ReplyAction="http://tempuri.org/IListePersonali/CreaListaPersonaleResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IListePersonali/CreaListaPersonaleBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    void CreaListaPersonale(string nome, string genere, string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListePersonali/CreaListaPersonale", ReplyAction="http://tempuri.org/IListePersonali/CreaListaPersonaleResponse")]
    System.Threading.Tasks.Task CreaListaPersonaleAsync(string nome, string genere, string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListePersonali/PubblicaListaPersonale", ReplyAction="http://tempuri.org/IListePersonali/PubblicaListaPersonaleResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IListePersonali/PubblicaListaPersonaleBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    void PubblicaListaPersonale(Progetto_Symposion.Lista lista);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListePersonali/PubblicaListaPersonale", ReplyAction="http://tempuri.org/IListePersonali/PubblicaListaPersonaleResponse")]
    System.Threading.Tasks.Task PubblicaListaPersonaleAsync(Progetto_Symposion.Lista lista);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListePersonali/ModificaListaPersonale", ReplyAction="http://tempuri.org/IListePersonali/ModificaListaPersonaleResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IListePersonali/ModificaListaPersonaleBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    void ModificaListaPersonale(Progetto_Symposion.Lista lista);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListePersonali/ModificaListaPersonale", ReplyAction="http://tempuri.org/IListePersonali/ModificaListaPersonaleResponse")]
    System.Threading.Tasks.Task ModificaListaPersonaleAsync(Progetto_Symposion.Lista lista);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListeSalvate/SalvaLista", ReplyAction="http://tempuri.org/IListeSalvate/SalvaListaResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IListeSalvate/SalvaListaBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    void SalvaLista(Progetto_Symposion.Lista lista, string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListeSalvate/SalvaLista", ReplyAction="http://tempuri.org/IListeSalvate/SalvaListaResponse")]
    System.Threading.Tasks.Task SalvaListaAsync(Progetto_Symposion.Lista lista, string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListeSalvate/RimuoviLista", ReplyAction="http://tempuri.org/IListeSalvate/RimuoviListaResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IListeSalvate/RimuoviListaBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    void RimuoviLista(Progetto_Symposion.Lista lista, string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IListeSalvate/RimuoviLista", ReplyAction="http://tempuri.org/IListeSalvate/RimuoviListaResponse")]
    System.Threading.Tasks.Task RimuoviListaAsync(Progetto_Symposion.Lista lista, string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecensioniSalvate/SalvaRecensione", ReplyAction="http://tempuri.org/IRecensioniSalvate/SalvaRecensioneResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IRecensioniSalvate/SalvaRecensioneBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    void SalvaRecensione(Progetto_Symposion.Recensione recensione, string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecensioniSalvate/SalvaRecensione", ReplyAction="http://tempuri.org/IRecensioniSalvate/SalvaRecensioneResponse")]
    System.Threading.Tasks.Task SalvaRecensioneAsync(Progetto_Symposion.Recensione recensione, string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecensioniSalvate/RimuoviRecensione", ReplyAction="http://tempuri.org/IRecensioniSalvate/RimuoviRecensioneResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IRecensioniSalvate/RimuoviRecensioneBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    void RimuoviRecensione(Progetto_Symposion.Recensione recensione, string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRecensioniSalvate/RimuoviRecensione", ReplyAction="http://tempuri.org/IRecensioniSalvate/RimuoviRecensioneResponse")]
    System.Threading.Tasks.Task RimuoviRecensioneAsync(Progetto_Symposion.Recensione recensione, string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISegnalazioni/AddSegnalazioneLibro", ReplyAction="http://tempuri.org/ISegnalazioni/AddSegnalazioneLibroResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/ISegnalazioni/AddSegnalazioneLibroBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    void AddSegnalazioneLibro(Progetto_Symposion.SegnalazioneLibro segnalazioneLibro);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISegnalazioni/AddSegnalazioneLibro", ReplyAction="http://tempuri.org/ISegnalazioni/AddSegnalazioneLibroResponse")]
    System.Threading.Tasks.Task AddSegnalazioneLibroAsync(Progetto_Symposion.SegnalazioneLibro segnalazioneLibro);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISegnalazioni/AddSegnalazioneRecensione", ReplyAction="http://tempuri.org/ISegnalazioni/AddSegnalazioneRecensioneResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/ISegnalazioni/AddSegnalazioneRecensioneBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    void AddSegnalazioneRecensione(Progetto_Symposion.SegnalazioneRecensione segnalazioneRecensione);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISegnalazioni/AddSegnalazioneRecensione", ReplyAction="http://tempuri.org/ISegnalazioni/AddSegnalazioneRecensioneResponse")]
    System.Threading.Tasks.Task AddSegnalazioneRecensioneAsync(Progetto_Symposion.SegnalazioneRecensione segnalazioneRecensione);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInserimentoLibro/InserisciLibroCover", ReplyAction="http://tempuri.org/IInserimentoLibro/InserisciLibroCoverResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IInserimentoLibro/InserisciLibroCoverBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    void InserisciLibroCover(string titolo, string autore, System.Nullable<int> anno, string gen, string cover, string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInserimentoLibro/InserisciLibroCover", ReplyAction="http://tempuri.org/IInserimentoLibro/InserisciLibroCoverResponse")]
    System.Threading.Tasks.Task InserisciLibroCoverAsync(string titolo, string autore, System.Nullable<int> anno, string gen, string cover, string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInserimentoLibro/InserisciLibro", ReplyAction="http://tempuri.org/IInserimentoLibro/InserisciLibroResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IInserimentoLibro/InserisciLibroBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    void InserisciLibro(string titolo, string autore, System.Nullable<int> anno, string gen, string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IInserimentoLibro/InserisciLibro", ReplyAction="http://tempuri.org/IInserimentoLibro/InserisciLibroResponse")]
    System.Threading.Tasks.Task InserisciLibroAsync(string titolo, string autore, System.Nullable<int> anno, string gen, string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRicercaPubblica/CercaRecensioniLibro", ReplyAction="http://tempuri.org/IRicercaPubblica/CercaRecensioniLibroResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IRicercaPubblica/CercaRecensioniLibroBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    Progetto_Symposion.Recensione[] CercaRecensioniLibro(Progetto_Symposion.Libro libro);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRicercaPubblica/CercaRecensioniLibro", ReplyAction="http://tempuri.org/IRicercaPubblica/CercaRecensioniLibroResponse")]
    System.Threading.Tasks.Task<Progetto_Symposion.Recensione[]> CercaRecensioniLibroAsync(Progetto_Symposion.Libro libro);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRicercaPubblica/CercaLibro", ReplyAction="http://tempuri.org/IRicercaPubblica/CercaLibroResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IRicercaPubblica/CercaLibroBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    Progetto_Symposion.Libro[] CercaLibro(string titolo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRicercaPubblica/CercaLibro", ReplyAction="http://tempuri.org/IRicercaPubblica/CercaLibroResponse")]
    System.Threading.Tasks.Task<Progetto_Symposion.Libro[]> CercaLibroAsync(string titolo);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRicercaPubblica/CercaLista", ReplyAction="http://tempuri.org/IRicercaPubblica/CercaListaResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IRicercaPubblica/CercaListaBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    Progetto_Symposion.Lista[] CercaLista(string nome);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRicercaPubblica/CercaLista", ReplyAction="http://tempuri.org/IRicercaPubblica/CercaListaResponse")]
    System.Threading.Tasks.Task<Progetto_Symposion.Lista[]> CercaListaAsync(string nome);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRicercaPubblica/CercaGenere", ReplyAction="http://tempuri.org/IRicercaPubblica/CercaGenereResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IRicercaPubblica/CercaGenereBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    Progetto_Symposion.Libro[] CercaGenere(string genere);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRicercaPubblica/CercaGenere", ReplyAction="http://tempuri.org/IRicercaPubblica/CercaGenereResponse")]
    System.Threading.Tasks.Task<Progetto_Symposion.Libro[]> CercaGenereAsync(string genere);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRicercaPubblica/CercaUtente", ReplyAction="http://tempuri.org/IRicercaPubblica/CercaUtenteResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IRicercaPubblica/CercaUtenteBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    string CercaUtente(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRicercaPubblica/CercaUtente", ReplyAction="http://tempuri.org/IRicercaPubblica/CercaUtenteResponse")]
    System.Threading.Tasks.Task<string> CercaUtenteAsync(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRicercaPubblica/CercaListaUtente", ReplyAction="http://tempuri.org/IRicercaPubblica/CercaListaUtenteResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IRicercaPubblica/CercaListaUtenteBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    Progetto_Symposion.Lista[] CercaListaUtente(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRicercaPubblica/CercaListaUtente", ReplyAction="http://tempuri.org/IRicercaPubblica/CercaListaUtenteResponse")]
    System.Threading.Tasks.Task<Progetto_Symposion.Lista[]> CercaListaUtenteAsync(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRicercaPubblica/CercaRecensioniUtente", ReplyAction="http://tempuri.org/IRicercaPubblica/CercaRecensioniUtenteResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IRicercaPubblica/CercaRecensioniUtenteBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    Progetto_Symposion.Recensione[] CercaRecensioniUtente(string usernameUtente);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRicercaPubblica/CercaRecensioniUtente", ReplyAction="http://tempuri.org/IRicercaPubblica/CercaRecensioniUtenteResponse")]
    System.Threading.Tasks.Task<Progetto_Symposion.Recensione[]> CercaRecensioniUtenteAsync(string usernameUtente);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRicercaPubblica/CercaListaPersonaleUtente", ReplyAction="http://tempuri.org/IRicercaPubblica/CercaListaPersonaleUtenteResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IRicercaPubblica/CercaListaPersonaleUtenteBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    Progetto_Symposion.Lista[] CercaListaPersonaleUtente(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IRicercaPubblica/CercaListaPersonaleUtente", ReplyAction="http://tempuri.org/IRicercaPubblica/CercaListaPersonaleUtenteResponse")]
    System.Threading.Tasks.Task<Progetto_Symposion.Lista[]> CercaListaPersonaleUtenteAsync(string username);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassifica/GetClassificaGenere", ReplyAction="http://tempuri.org/IClassifica/GetClassificaGenereResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IClassifica/GetClassificaGenereBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    Progetto_Symposion.Libro[] GetClassificaGenere(string gen);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassifica/GetClassificaGenere", ReplyAction="http://tempuri.org/IClassifica/GetClassificaGenereResponse")]
    System.Threading.Tasks.Task<Progetto_Symposion.Libro[]> GetClassificaGenereAsync(string gen);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassifica/GetClassificaAnno", ReplyAction="http://tempuri.org/IClassifica/GetClassificaAnnoResponse")]
    [System.ServiceModel.FaultContractAttribute(typeof(SymposionUtenteLib.BookFault), Action="http://tempuri.org/IClassifica/GetClassificaAnnoBookFaultFault", Name="BookFault", Namespace="http://schemas.datacontract.org/2004/07/SymposionUtenteLib")]
    Progetto_Symposion.Libro[] GetClassificaAnno(int date);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IClassifica/GetClassificaAnno", ReplyAction="http://tempuri.org/IClassifica/GetClassificaAnnoResponse")]
    System.Threading.Tasks.Task<Progetto_Symposion.Libro[]> GetClassificaAnnoAsync(int date);
    
    // CODEGEN: Generazione di un contratto di messaggio perché il nome wrapper (DownloadRequest) del messaggio DownloadRequest non corrisponde al valore predefinito (DownloadFile)
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtente/DownloadFile", ReplyAction="http://tempuri.org/IUtente/DownloadFileResponse")]
    RemoteFileInfo DownloadFile(DownloadRequest request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtente/DownloadFile", ReplyAction="http://tempuri.org/IUtente/DownloadFileResponse")]
    System.Threading.Tasks.Task<RemoteFileInfo> DownloadFileAsync(DownloadRequest request);
    
    // CODEGEN: Generazione di un contratto di messaggio perché l'operazione UploadFile non è RPC né incapsulata da documenti.
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtente/UploadFile", ReplyAction="http://tempuri.org/IUtente/UploadFileResponse")]
    UploadFileResponse UploadFile(RemoteFileInfo request);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IUtente/UploadFile", ReplyAction="http://tempuri.org/IUtente/UploadFileResponse")]
    System.Threading.Tasks.Task<UploadFileResponse> UploadFileAsync(RemoteFileInfo request);
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="DownloadRequest", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class DownloadRequest
{
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public string FileName;
    
    public DownloadRequest()
    {
    }
    
    public DownloadRequest(string FileName)
    {
        this.FileName = FileName;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(WrapperName="RemoteFileInfo", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
public partial class RemoteFileInfo
{
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
    public string FileName;
    
    [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
    public long Length;
    
    [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
    public System.IO.Stream FileByteStream;
    
    public RemoteFileInfo()
    {
    }
    
    public RemoteFileInfo(string FileName, long Length, System.IO.Stream FileByteStream)
    {
        this.FileName = FileName;
        this.Length = Length;
        this.FileByteStream = FileByteStream;
    }
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
[System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
public partial class UploadFileResponse
{
    
    public UploadFileResponse()
    {
    }
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IUtenteChannel : IUtente, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class UtenteClient : System.ServiceModel.ClientBase<IUtente>, IUtente
{
    
    public UtenteClient()
    {
    }
    
    public UtenteClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public UtenteClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UtenteClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public UtenteClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public Progetto_Symposion.Recensione[] GetRecensioniScritte(string username)
    {
        return base.Channel.GetRecensioniScritte(username);
    }
    
    public System.Threading.Tasks.Task<Progetto_Symposion.Recensione[]> GetRecensioniScritteAsync(string username)
    {
        return base.Channel.GetRecensioniScritteAsync(username);
    }
    
    public Progetto_Symposion.Lista[] GetListePersonali(string username)
    {
        return base.Channel.GetListePersonali(username);
    }
    
    public System.Threading.Tasks.Task<Progetto_Symposion.Lista[]> GetListePersonaliAsync(string username)
    {
        return base.Channel.GetListePersonaliAsync(username);
    }
    
    public Progetto_Symposion.Recensione[] GetRecensioniSalvate(string username)
    {
        return base.Channel.GetRecensioniSalvate(username);
    }
    
    public System.Threading.Tasks.Task<Progetto_Symposion.Recensione[]> GetRecensioniSalvateAsync(string username)
    {
        return base.Channel.GetRecensioniSalvateAsync(username);
    }
    
    public Progetto_Symposion.Lista[] GetListeSalvate(string username)
    {
        return base.Channel.GetListeSalvate(username);
    }
    
    public System.Threading.Tasks.Task<Progetto_Symposion.Lista[]> GetListeSalvateAsync(string username)
    {
        return base.Channel.GetListeSalvateAsync(username);
    }
    
    public void PubblicaRecensione(System.Nullable<int> punteggio, string commento, Progetto_Symposion.Libro libro, string username)
    {
        base.Channel.PubblicaRecensione(punteggio, commento, libro, username);
    }
    
    public System.Threading.Tasks.Task PubblicaRecensioneAsync(System.Nullable<int> punteggio, string commento, Progetto_Symposion.Libro libro, string username)
    {
        return base.Channel.PubblicaRecensioneAsync(punteggio, commento, libro, username);
    }
    
    public void ModificaRecensione(Progetto_Symposion.Recensione recensione)
    {
        base.Channel.ModificaRecensione(recensione);
    }
    
    public System.Threading.Tasks.Task ModificaRecensioneAsync(Progetto_Symposion.Recensione recensione)
    {
        return base.Channel.ModificaRecensioneAsync(recensione);
    }
    
    public void CreaListaPersonale(string nome, string genere, string username)
    {
        base.Channel.CreaListaPersonale(nome, genere, username);
    }
    
    public System.Threading.Tasks.Task CreaListaPersonaleAsync(string nome, string genere, string username)
    {
        return base.Channel.CreaListaPersonaleAsync(nome, genere, username);
    }
    
    public void PubblicaListaPersonale(Progetto_Symposion.Lista lista)
    {
        base.Channel.PubblicaListaPersonale(lista);
    }
    
    public System.Threading.Tasks.Task PubblicaListaPersonaleAsync(Progetto_Symposion.Lista lista)
    {
        return base.Channel.PubblicaListaPersonaleAsync(lista);
    }
    
    public void ModificaListaPersonale(Progetto_Symposion.Lista lista)
    {
        base.Channel.ModificaListaPersonale(lista);
    }
    
    public System.Threading.Tasks.Task ModificaListaPersonaleAsync(Progetto_Symposion.Lista lista)
    {
        return base.Channel.ModificaListaPersonaleAsync(lista);
    }
    
    public void SalvaLista(Progetto_Symposion.Lista lista, string username)
    {
        base.Channel.SalvaLista(lista, username);
    }
    
    public System.Threading.Tasks.Task SalvaListaAsync(Progetto_Symposion.Lista lista, string username)
    {
        return base.Channel.SalvaListaAsync(lista, username);
    }
    
    public void RimuoviLista(Progetto_Symposion.Lista lista, string username)
    {
        base.Channel.RimuoviLista(lista, username);
    }
    
    public System.Threading.Tasks.Task RimuoviListaAsync(Progetto_Symposion.Lista lista, string username)
    {
        return base.Channel.RimuoviListaAsync(lista, username);
    }
    
    public void SalvaRecensione(Progetto_Symposion.Recensione recensione, string username)
    {
        base.Channel.SalvaRecensione(recensione, username);
    }
    
    public System.Threading.Tasks.Task SalvaRecensioneAsync(Progetto_Symposion.Recensione recensione, string username)
    {
        return base.Channel.SalvaRecensioneAsync(recensione, username);
    }
    
    public void RimuoviRecensione(Progetto_Symposion.Recensione recensione, string username)
    {
        base.Channel.RimuoviRecensione(recensione, username);
    }
    
    public System.Threading.Tasks.Task RimuoviRecensioneAsync(Progetto_Symposion.Recensione recensione, string username)
    {
        return base.Channel.RimuoviRecensioneAsync(recensione, username);
    }
    
    public void AddSegnalazioneLibro(Progetto_Symposion.SegnalazioneLibro segnalazioneLibro)
    {
        base.Channel.AddSegnalazioneLibro(segnalazioneLibro);
    }
    
    public System.Threading.Tasks.Task AddSegnalazioneLibroAsync(Progetto_Symposion.SegnalazioneLibro segnalazioneLibro)
    {
        return base.Channel.AddSegnalazioneLibroAsync(segnalazioneLibro);
    }
    
    public void AddSegnalazioneRecensione(Progetto_Symposion.SegnalazioneRecensione segnalazioneRecensione)
    {
        base.Channel.AddSegnalazioneRecensione(segnalazioneRecensione);
    }
    
    public System.Threading.Tasks.Task AddSegnalazioneRecensioneAsync(Progetto_Symposion.SegnalazioneRecensione segnalazioneRecensione)
    {
        return base.Channel.AddSegnalazioneRecensioneAsync(segnalazioneRecensione);
    }
    
    public void InserisciLibroCover(string titolo, string autore, System.Nullable<int> anno, string gen, string cover, string username)
    {
        base.Channel.InserisciLibroCover(titolo, autore, anno, gen, cover, username);
    }
    
    public System.Threading.Tasks.Task InserisciLibroCoverAsync(string titolo, string autore, System.Nullable<int> anno, string gen, string cover, string username)
    {
        return base.Channel.InserisciLibroCoverAsync(titolo, autore, anno, gen, cover, username);
    }
    
    public void InserisciLibro(string titolo, string autore, System.Nullable<int> anno, string gen, string username)
    {
        base.Channel.InserisciLibro(titolo, autore, anno, gen, username);
    }
    
    public System.Threading.Tasks.Task InserisciLibroAsync(string titolo, string autore, System.Nullable<int> anno, string gen, string username)
    {
        return base.Channel.InserisciLibroAsync(titolo, autore, anno, gen, username);
    }
    
    public Progetto_Symposion.Recensione[] CercaRecensioniLibro(Progetto_Symposion.Libro libro)
    {
        return base.Channel.CercaRecensioniLibro(libro);
    }
    
    public System.Threading.Tasks.Task<Progetto_Symposion.Recensione[]> CercaRecensioniLibroAsync(Progetto_Symposion.Libro libro)
    {
        return base.Channel.CercaRecensioniLibroAsync(libro);
    }
    
    public Progetto_Symposion.Libro[] CercaLibro(string titolo)
    {
        return base.Channel.CercaLibro(titolo);
    }
    
    public System.Threading.Tasks.Task<Progetto_Symposion.Libro[]> CercaLibroAsync(string titolo)
    {
        return base.Channel.CercaLibroAsync(titolo);
    }
    
    public Progetto_Symposion.Lista[] CercaLista(string nome)
    {
        return base.Channel.CercaLista(nome);
    }
    
    public System.Threading.Tasks.Task<Progetto_Symposion.Lista[]> CercaListaAsync(string nome)
    {
        return base.Channel.CercaListaAsync(nome);
    }
    
    public Progetto_Symposion.Libro[] CercaGenere(string genere)
    {
        return base.Channel.CercaGenere(genere);
    }
    
    public System.Threading.Tasks.Task<Progetto_Symposion.Libro[]> CercaGenereAsync(string genere)
    {
        return base.Channel.CercaGenereAsync(genere);
    }
    
    public string CercaUtente(string username)
    {
        return base.Channel.CercaUtente(username);
    }
    
    public System.Threading.Tasks.Task<string> CercaUtenteAsync(string username)
    {
        return base.Channel.CercaUtenteAsync(username);
    }
    
    public Progetto_Symposion.Lista[] CercaListaUtente(string username)
    {
        return base.Channel.CercaListaUtente(username);
    }
    
    public System.Threading.Tasks.Task<Progetto_Symposion.Lista[]> CercaListaUtenteAsync(string username)
    {
        return base.Channel.CercaListaUtenteAsync(username);
    }
    
    public Progetto_Symposion.Recensione[] CercaRecensioniUtente(string usernameUtente)
    {
        return base.Channel.CercaRecensioniUtente(usernameUtente);
    }
    
    public System.Threading.Tasks.Task<Progetto_Symposion.Recensione[]> CercaRecensioniUtenteAsync(string usernameUtente)
    {
        return base.Channel.CercaRecensioniUtenteAsync(usernameUtente);
    }
    
    public Progetto_Symposion.Lista[] CercaListaPersonaleUtente(string username)
    {
        return base.Channel.CercaListaPersonaleUtente(username);
    }
    
    public System.Threading.Tasks.Task<Progetto_Symposion.Lista[]> CercaListaPersonaleUtenteAsync(string username)
    {
        return base.Channel.CercaListaPersonaleUtenteAsync(username);
    }
    
    public Progetto_Symposion.Libro[] GetClassificaGenere(string gen)
    {
        return base.Channel.GetClassificaGenere(gen);
    }
    
    public System.Threading.Tasks.Task<Progetto_Symposion.Libro[]> GetClassificaGenereAsync(string gen)
    {
        return base.Channel.GetClassificaGenereAsync(gen);
    }
    
    public Progetto_Symposion.Libro[] GetClassificaAnno(int date)
    {
        return base.Channel.GetClassificaAnno(date);
    }
    
    public System.Threading.Tasks.Task<Progetto_Symposion.Libro[]> GetClassificaAnnoAsync(int date)
    {
        return base.Channel.GetClassificaAnnoAsync(date);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    RemoteFileInfo IUtente.DownloadFile(DownloadRequest request)
    {
        return base.Channel.DownloadFile(request);
    }
    
    public long DownloadFile(ref string FileName, out System.IO.Stream FileByteStream)
    {
        DownloadRequest inValue = new DownloadRequest();
        inValue.FileName = FileName;
        RemoteFileInfo retVal = ((IUtente)(this)).DownloadFile(inValue);
        FileName = retVal.FileName;
        FileByteStream = retVal.FileByteStream;
        return retVal.Length;
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<RemoteFileInfo> IUtente.DownloadFileAsync(DownloadRequest request)
    {
        return base.Channel.DownloadFileAsync(request);
    }
    
    public System.Threading.Tasks.Task<RemoteFileInfo> DownloadFileAsync(string FileName)
    {
        DownloadRequest inValue = new DownloadRequest();
        inValue.FileName = FileName;
        return ((IUtente)(this)).DownloadFileAsync(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    UploadFileResponse IUtente.UploadFile(RemoteFileInfo request)
    {
        return base.Channel.UploadFile(request);
    }
    
    public void UploadFile(string FileName, long Length, System.IO.Stream FileByteStream)
    {
        RemoteFileInfo inValue = new RemoteFileInfo();
        inValue.FileName = FileName;
        inValue.Length = Length;
        inValue.FileByteStream = FileByteStream;
        UploadFileResponse retVal = ((IUtente)(this)).UploadFile(inValue);
    }
    
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    System.Threading.Tasks.Task<UploadFileResponse> IUtente.UploadFileAsync(RemoteFileInfo request)
    {
        return base.Channel.UploadFileAsync(request);
    }
    
    public System.Threading.Tasks.Task<UploadFileResponse> UploadFileAsync(string FileName, long Length, System.IO.Stream FileByteStream)
    {
        RemoteFileInfo inValue = new RemoteFileInfo();
        inValue.FileName = FileName;
        inValue.Length = Length;
        inValue.FileByteStream = FileByteStream;
        return ((IUtente)(this)).UploadFileAsync(inValue);
    }
}
